### ISSUE TITLE
Make code conform to Pony style guide

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/corral#11]
It almost assuredly doesn't.

Given this will touch a lot of code, if you can't do this in a fairly quick go, to avoid merge conflicts, it would be best to do in short increments that can be done off of latest master and merged quickly.

Perhaps a module at a time.

**Comment by cquinn** [comment]
What are the main offenses? 
* Extra blank lines between top-level items
* Line length > 80?

**Comment by cquinn** [comment]
We need a Pony linter / formatter.

**Comment by SeanTAllen** [comment]
No idea what they would be, I only glanced, but I'm 99% sure at least some exist.

@Theodus spots em like crazy because he wrote the style guide.

**Comment by cquinn** [comment]
OK to close this one now?

**Comment by SeanTAllen** [comment]
I thought I had!

**Comment by EpicEric** [comment]
@cquinn, just as a tip, you can use [keywords in GitHub](https://help.github.com/en/articles/closing-issues-using-keywords) to auto-close issues once a PR is merged.
