### ISSUE TITLE
Corral PONYPATH constructor uses incorrect separator on Windows

### ISSUE THREAD

**Issue by btab** [ponylang/corral#116]
https://github.com/ponylang/corral/blob/3b29efb6ab4c874b6bbdf441f161c3874445cd93/corral/cmd/cmd_run.pony#L27

...needs to use ';' on Windows per the logic in ponyc...

https://github.com/ponylang/ponyc/blob/234d26895d5dfdc124e984272e11f37f78ce5e6e/src/libponyc/pkg/package.c#L29

**Comment by btab** [comment]
Do we have a platform-aware path separator constant somewhere in the standard library?

**Comment by mfelsche** [comment]
Good catch!
We have: https://stdlib.ponylang.io/files-Path/#list_sep
