### ISSUE TITLE
Add install command support

### ISSUE THREAD

**Issue by damon-kwok** [ponylang/corral#145]
It is similar to cargo's install command
- install     Install a Pony binary. Default location is $HOME/.corral/bin
- uninstall   Uninstall a Pony binary

```bash
cargo install ripgrep
```
```bash
corral install jylis
corral install pony-tags
```

**Comment by SeanTAllen** [comment]
Starting from a very simple place, how would corral find things to install?

Why would we make a dependency and build tool become a tool for installing applications?

**Comment by SeanTAllen** [comment]
Closing as this is out of scope for corral at this time. We have ponyup for installing applications.
