### ISSUE TITLE
Trying out corral first time and received Error: required bundle files not found 

### ISSUE THREAD

**Issue by adeel41** [ponylang/corral#148]
Hi, just letting you know a newbie experience. Started learning pony few days ago, learned about corral and this morning give it a try.  Attaching a screenshot which might explain how it went,

![image](https://user-images.githubusercontent.com/13577/87774848-08795e80-c81d-11ea-88c6-53ba29e84697.png)

So initially I get an error that says "required bundle files not found in or above current directory" which is quite confusing because i don't know which file is expected. and there is no step mentioned on the main page which explains that I need to have a `corral.json` file which must have following json 
```
{
  "deps": [],
  "info": {}
}
```

I had to look at some of the other pony projects that which bits am i missing and glad that eventually it worked.

I think either this small piece of information should be mentioned for pony newbie like me or may be `corral` should create a json file if it doesn't exist? and then add the entry?

**Comment by damon-kwok** [comment]
@adeel41 
```sh
mkdir myproject
cd myproject
corral init
```

**Comment by adeel41** [comment]
thanks for that @damon-kwok 

I was following this snippet which is on the project page. and it does not mention that step. But thanks i'll remember that now

```
mkdir myproject && cd myproject

corral add github.com/jemc/pony-inspect.git

echo '
use "inspect"
actor Main
  new create(env: Env) =>
    env.out.print(Inspect("Hello, World!"))
' > main.pony
```

**Comment by damon-kwok** [comment]
@adeel41  Can you submit a PR to fix document? I think this is very welcome :)

**Comment by adeel41** [comment]
sure @damon-kwok . Just learning more bits and pieces :D I was trying to run using corral but didn't realize that i need to fetch dependencies first. (which I learned again by looking at some other repos which are using corral)

I think there should be a new section just to explain all of these things. i.e. You need to `corral init` and do `corral fetch` and then `corral run -- ponyc .`

I get that why it isn't mentioned in the current form because it is just explaining you can either use git repo providers or use local git repo or direct bundle.

I'll create a PR and add a section to explain what to do if it is your first time with corral

**Comment by damon-kwok** [comment]
The `Ponylang` community is driven by volunteers. Welcome to join :)

**Comment by SeanTAllen** [comment]
@adeel41 those sound like valuable additions to documentation.
