### ISSUE TITLE
Transition from stable is currently problematic

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/corral#17]
There's a problem right now with using corral with various dependencies. If that dependency has a "Stable" format `bundle.json` then corral will try to operate on it and choke.

I think that we should take 1 of 2 possible approaches

## stable format support

For a while, we should add support to handle stable format `bundle.json` files to corral so corral can do its thing with them in terms of handling transitive dependencies.

## don't use `bundle.json`

The other option is to make a clean break and change the name of `bundle.json` for corral to something like `corral.json`.

**Comment by rkallos** [comment]
One point in favor of `corral.json` is that it signals the name of the tool to use, a bit like `rebar3` in Erlang. `bundle.json` is a bit ambiguous in that respect. It can also allow for both stable and corral to be used to build the same project even if their metadata schemas diverge.

+1 for `corral.json` here :)

**Comment by aturley** [comment]
I'm also in favor of using `corral.json` for the reasons @rkallos mentioned.
