### ISSUE TITLE
Most of the ponylang projects uses `main` for the master branch, but corral still tries to checkout to `master`

### ISSUE THREAD

**Issue by no1xsyzy** [ponylang/corral#174]
So following the Installation section (e.g. [`http` repo](https://github.com/ponylang/http#installation)) will fail.
```
  exit: Exited(128)
  out:
  err: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

There seems 3 ways to deal with it.

1. Use `main` as default.
2. Check `main` and `master` and choose the more recent one.
3. Doc `--revision=main` to the installation section of every project.

**Comment by SeanTAllen** [comment]
This has already been addressed. It hasn't however been released. It will be released the weekend of the 26th. It's available in nightly builds that the default is "main" if no other version is given. Really, a version or hash should be set by the user.

https://github.com/ponylang/corral/pull/171
