### ISSUE TITLE
`corral run` only accepts argv[0] if it's in $PATH

### ISSUE THREAD

**Issue by rkallos** [ponylang/corral#18]
To replicate:
`corral run /path/to/alternate/ponyc`

[cmd_run.pony:39](https://github.com/ponylang/corral/blob/master/corral/cmd/cmd_run.pony#L39) checks that the first argument to `corral run` is in $PATH. This might cause frustration if people test with different versions of `ponyc` than the one in $PATH.

One solution to this might be to replace that check with a more permissive one, like making sure the file specified by the argument exists (or is in $PATH) and is executable.

**Comment by SeanTAllen** [comment]
I believe that @Theodus is thinking of making PATH munging part of `ponyup` which might make this less of an issue. 

I guess the biggest question here is, is this a security issue or just a "it's executable". I imagine its more the "it's executable" in which case exists and is executable is a reasonable change to me.
