### ISSUE TITLE
TODO item: Add a --path flag to allow specification of bundle dir to start in

### ISSUE THREAD

**Issue by cquinn** [ponylang/corral#23]
The current behavior is to start at CWD and search up until a bundle.json is found. We should have an option to supply the directory to load the bundle.json from, bypassing the search.

**Comment by ordepdev** [comment]
This should be included in **all** commands? For starters, I was able to add this `--path` flag to the `init` command. I just want to make sure that adding this flag to all commands makes sense.

**Comment by ordepdev** [comment]
```bash
corral[master*] % build/release/corral init --path ".."

init: from dir ..
INFO: Created bundle in /Users/ordepdev/Work
FINE: Going to write /Users/ordepdev/Work/bundle.json
INFO: Writing /Users/ordepdev/Work/bundle.json
FINE: Going to write /Users/ordepdev/Work/lock.json
INFO: Writing /Users/ordepdev/Work/lock.json
INFO: init: created: Work
```

This should be valid, right?

**Comment by SeanTAllen** [comment]
@ordepdev any command that otherwise has an implicit path yes. For example, a `version` command doesn't have an implicit path but `init` does.

**Comment by cquinn** [comment]
PR #60 changes this `--path` or `--directory` to `--bundle_dir` since it overrides specifically the base directory of the bundle (where the corral.json and lock.json files are, and where the _corral/ subdir live)
