### ISSUE TITLE
TODO item: Allow for non-semver constraints, such as simple tags or branches

### ISSUE THREAD

**Issue by cquinn** [ponylang/corral#26]
We would need to define a clear notation for indicating the kind of version constraint.

**Comment by SeanTAllen** [comment]
The ability to do this with stable was definitely valuable to us at Wallaroo Labs, particularly when doing development. With stable, the value is "just whatever you pass to `git checkout`" or similar. What is the issue with doing that with corral? I think the answer to that question will really help guide a conversation re: "clear notation".

**Comment by cquinn** [comment]
I think it is mainly in distinguishing a semver expression that has to be processed from a simple tag that can be just passed through. This is probably really simple and mostly a doc change.

**Comment by cquinn** [comment]
If it can't be parsed as a constraint, starting with: "<="; "<"; ">="; ">"; "="; "^"; "~" 
then it will be treated as a revision (commit-ish) to be passed to git.
