### ISSUE TITLE
TODO item: Honor `-n` everywhere.

### ISSUE THREAD

**Issue by cquinn** [ponylang/corral#27]
Make sure that no commands modify anything when -n (nothing == true) is set.

**Comment by SeanTAllen** [comment]
Is `-n` a dry run command?

**Comment by cquinn** [comment]
Exactly.

**Comment by SeanTAllen** [comment]
Are you aware of commands that currently aren't honoring `-n`?

**Comment by cquinn** [comment]
I think none of them honor it :)

**Comment by cquinn** [comment]
We might want to decide if touching the cache counts as a modification. If not, then some commands might want to pull repos into the cache to then produce more details about what they would do.
