### ISSUE TITLE
TODO item: Implement remote gitlabs repos

### ISSUE THREAD

**Issue by cquinn** [ponylang/corral#32]
This should be like Github, but maybe there are nuances to deal with.

**Comment by SeanTAllen** [comment]
I don't understand this one. Given that it's git, what is there to do? With stable, all that had to be done with this was add support for gitlib.com as a url you could pull from. I don't think there's anything to do for this one.

We should get someone to test to verify.

**Comment by cquinn** [comment]
You are probably right, but I had never tested it.

**Comment by cquinn** [comment]
The new tests for them work fine. They did work exactly like github.
