### ISSUE TITLE
TODO item: Implement local repos

### ISSUE THREAD

**Issue by cquinn** [ponylang/corral#33]
For local repos we should be able to skip the clone and fetch steps, and just do a direct checkout.

**Comment by SeanTAllen** [comment]
We found these to be incredibly valuable at Wallaroo Labs when we were doing development. Definitely a feature we want to add.

**Comment by cquinn** [comment]
To clarify, a local repo differs from a local path in that Corral would still use the VCS to pull its own workspace from local VCS repo and not use that repo's normal workspace.
