### ISSUE TITLE
TODO item: Implement local paths

### ISSUE THREAD

**Issue by cquinn** [ponylang/corral#34]
For local paths we should be able to skip the clone and fetch steps, and version/tag queries and checkout using symlink or copy or logical reference path in PONYPATH.

Maybe this can be done via a special "local" VCS.

**Comment by SeanTAllen** [comment]
What in your mind is the difference between a local path and a local repo?

**Comment by cquinn** [comment]
A local path would be just a source tree at a local filesystem location. No VCS used (by Corral at least) and no versioning. Just the working tree.

**Comment by SeanTAllen** [comment]
I can see this being useful in a monorepo. We added a feature to stable to support the monorepo use case we have with Wallaroo.

**Comment by cquinn** [comment]
Yes. And also when you want to make it easy to work on two projects in parallel without interacting with the VCS.
