### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/corral#5]
There's no version or version info right now. Will need to be able to set.

**Comment by cquinn** [comment]
I think a new `version` command would work well for this. We could manage a semver version alone in a Pony source file and this command would display it along with anything else we think is interesting.

**Comment by SeanTAllen** [comment]
Agreed. For packaging, we want that version to be set via a -D which can then be read via Makefile from either "VERSION" file or overridden as an arg to `make`.
