### ISSUE TITLE
Replace "regex" library usage

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/corral#8]
Currently, the git cmd uses "regex" functionality. Once the `ci` branch is merged, we want to remove the vendored regex functionality that depends on PRCRE2 and use something that has no external dependencies to make bootstrapping corral easier.

To that end

- Regex using code should be rewritten
- README should have "how to install pcre2" removed
- "vendored" regex library should be removed

**Comment by SeanTAllen** [comment]
@EpicEric would you be up to taking this one on?

**Comment by cquinn** [comment]
I'm using a regex in only one place to parse the `git show-ref` output that looks like:
```
de8ac5e98995176fea96a841d603962b3d0aff80 refs/tags/0.24.4
232a0abe144767332dc95865235897782074bad3 refs/tags/0.25.0
3c0c29072d277d3d48f49d3f693633342542d82a refs/tags/0.26.0
```
We could instead use soething like `String.split()` then `String.at("refs/tags/")` then `String.substring(10)` for each line.

**Comment by EpicEric** [comment]
@rkallos wants to work on this, so I'll unassign myself

**Comment by EpicEric** [comment]
@cquinn A simpler solution would be:

```pony
let matched: Array[String] = line.split_by(" refs/tags/")
if matched.size() == 2 then
  let tg: String = matched(1)?
  tags.push(tg)
end
```
